name: Déploiement Planifié Cash Arena

on:
  schedule:
    # Les Crons sur GitHub utilisent le fuseau horaire UTC.
    # En France (Europe/Paris) : 
    # - En hiver (UTC+1), 21h00 correspond à 20h00 UTC.
    # - En été (UTC+2), 21h00 correspond à 19h00 UTC.
    # Ici configuré pour 20h00 UTC (0 20 * * 1 -> Minute 0, Heure 20, Tous les jours, Tous les mois, Jour 1 = Lundi)
    - cron: '0 20 * * 1'

jobs:
  trigger-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Déclencher le build Vercel
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
